// Служебные страницы, которых нет в макете: политика, условия, карта сайта.
module.exports = (BASE, ROUTES) => {
  const G = require('./gen_pages');
  const load = G.load, esc = G.helpers.esc;
  const directions = load('directions.json'), brands = load('brands.json'), products = load('products.json'), articles = load('articles.json');
  const li = (href, text) => `<li><a href="${href}">${esc(text)}</a></li>`;
  const cols = items => `<ul style="columns:3 220px;column-gap:28px;margin:0 0 8px">${items.join('')}</ul>`;
  const H3 = t => `<h3 style="font-size:17px;margin:18px 0 6px">${esc(t)}</h3>`;
  const R = id => BASE + ROUTES[id].path;
  const dirHref = d => BASE + (d.existing ? 'napravleniya/nasosy/' : `napravleniya/${d.slug}/`);
  const prodHref = p => BASE + `katalog/${p.category || 'kompressory'}/${p.slug}/`;
  const groupBy = (arr, f) => arr.reduce((m, x) => { const k = f(x); (m.get(k) || m.set(k, []).get(k)).push(x); return m; }, new Map());
  const profile = b => /подшип/i.test(b.h1 || '') ? 'Подшипники' : /частот|преобраз/i.test(b.h1 || '') ? 'Частотные преобразователи' : /компресс/i.test(b.h1 || '') ? 'Компрессоры' : /редукт|привод/i.test(b.h1 || '') ? 'Мотор-редукторы' : 'Насосы';
  const CAT2DIR = { nasosy: 'Насосы', armatura: 'Промышленная арматура', privod: 'Редукторы и мотор-редукторы', podshipniki: 'Подшипники и комплектующие', kompressory: 'Компрессоры', elektrika: 'Частотники и автоматика', pnevmatika: 'Пневматика', zapchasti: 'Запчасти для производства' };
  const allArticles = articles.some(a => a.slug === 'kak-podobrat-nasos-po-rabochej-tochke') ? articles : [{ slug: 'kak-podobrat-nasos-po-rabochej-tochke', title: 'Как подобрать насос по рабочей точке и не переплатить за напор', section: 'Подбор · Насосы' }, ...articles];
  const topic = a => ((a.section || '').split('·')[1] || a.section || '').trim();
  const SECTIONS = [
    ['Каталог и подбор', [[R('homeB'), 'Главная'], [R('directions'), 'Каталог: все направления'], [R('catalog'), 'Каталог насосов с фильтрами'], [BASE + 'katalog/armatura/', 'Каталог промышленной арматуры'], [BASE + 'katalog/privod/', 'Каталог редукторов и мотор-редукторов'], [BASE + 'katalog/podshipniki/', 'Каталог подшипников'], [BASE + 'katalog/kompressory/', 'Каталог компрессоров'], [BASE + 'katalog/elektrika/', 'Каталог частотников и автоматики'], [BASE + 'katalog/pnevmatika/', 'Каталог пневматики'], [BASE + 'katalog/zapchasti/', 'Каталог запчастей'], [BASE + 'proizvoditeli/', 'Производители оборудования'], [R('photo'), 'Поиск по фото шильдика'], [R('chat'), 'Подбор оборудования в чате'], [R('upload'), 'Заявка списком из Excel']]],
    ['Покупателям', [[R('payment'), 'Оплата и доставка'], [R('warranty'), 'Гарантия и возврат'], [R('project'), 'Проектные закупки'], [R('about'), 'О сервисе'], [BASE + 'kontakty/', 'Контакты']]],
    ['Поставщикам', [[R('supplier'), 'Поставщикам: подключение прайса'], [R('terms'), 'Условия для поставщиков']]],
    ['Блог и правовая информация', [[R('blog'), 'Инженерный блог'], [BASE + 'politika-konfidencialnosti/', 'Политика конфиденциальности'], [BASE + 'usloviya-ispolzovaniya/', 'Условия использования']]],
  ];
  const sitemap = `<h2>Разделы сайта</h2>${SECTIONS.map(([t, links]) => H3(t) + cols(links.map(([h, n]) => li(h, n)))).join('')}`
    + `<h2>Направления каталога <span style="font-weight:400;color:var(--color-neutral-600)">${directions.length}</span></h2>${[...groupBy(directions, d => d.cluster)].map(([c, list]) => H3(c) + cols(list.map(d => li(dirHref(d), d.name)))).join('')}`
    + `<h2>Производители <span style="font-weight:400;color:var(--color-neutral-600)">${brands.length}</span></h2>${[...groupBy(brands, profile)].map(([g, list]) => H3(g) + cols(list.map(b => li(`${BASE}proizvoditeli/${b.slug}/`, b.h1 || b.name)))).join('')}`
    + `<h2>Товары <span style="font-weight:400;color:var(--color-neutral-600)">${products.length}</span></h2>${[...groupBy(products, p => CAT2DIR[p.category] || p.categoryName || 'Прочее')].map(([g, list]) => H3(g) + cols(list.map(p => li(prodHref(p), p.name)))).join('')}`
    + `<h2>Статьи блога <span style="font-weight:400;color:var(--color-neutral-600)">${allArticles.length}</span></h2>${[...groupBy(allArticles, topic)].map(([g, list]) => H3(g) + cols(list.map(a => li(`${BASE}blog/${a.slug}/`, a.title)))).join('')}`;
  // «Полезные разделы» в конце служебных страниц; self — путь текущей страницы (на себя не ссылаемся)
  const useful = self => `<h2>Полезные разделы</h2><ul>${[[R('directions'), 'Каталог оборудования: 45 направлений'], [BASE + 'proizvoditeli/', 'Производители оборудования'], [R('payment'), 'Оплата, доставка и документы'], [R('warranty'), 'Гарантия, возврат и рекламации'], [R('photo'), 'Поиск оборудования по фото шильдика'], [R('supplier'), 'Поставщикам: подключение прайса'], [R('terms'), 'Условия для поставщиков: вопросы и ответы'], [BASE + 'kontakty/', 'Контакты'], [BASE + 'karta-sajta/', 'Карта сайта']].filter(([h]) => h !== BASE + self).map(([h, n]) => li(h, n)).join('')}</ul>`;
  const note = `<p class="pk-note">Сайт работает в демонстрационном режиме: формы и заказы не отправляются, реквизиты оператора будут опубликованы после регистрации юридического лица.</p>`;
  return [
    { path: 'karta-sajta/', index: true, h1: 'Карта сайта', title: 'Карта сайта — ПРОМКОНТУР', desc: `Все страницы ПРОМКОНТУР: ${directions.length} направлений каталога, ${brands.length} производителей, товары, статьи инженерного блога, оплата и доставка, гарантия, поставщикам.`, html: sitemap },
    { path: 'kontakty/', index: true, h1: 'Контакты', title: 'Контакты сервиса закупки оборудования — ПРОМКОНТУР', desc: 'Как связаться с ПРОМКОНТУР: чат в MAX и почта для заказов, отдельный адрес для поставщиков. Работаем пн–пт с 08:00 до 19:00 по Москве, КП — за 2 рабочих часа.',
      html: `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px;margin:4px 0 8px"><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-channel-max" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Чат в MAX</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)">Подбор, счёт и статус заказа в одной переписке. На сайте тот же движок — «<a href="${BASE}${ROUTES.chat.path}">Умный чат</a>».</span></div><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-channel-mail" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Почта заказов</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)"><a href="mailto:zakaz@promkontur.example">zakaz@promkontur.example</a> — заявки списком, опросные листы, реквизиты для счёта.</span></div><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-channel-vendor" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Почта для поставщиков</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)"><a href="mailto:partner@promkontur.example">partner@promkontur.example</a> — подключение прайса, условия и расчёты.</span></div><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-ui-history" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Часы работы</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)">Пн–пт, 08:00–19:00 по Москве. КП — за 2 рабочих часа, счёт на позиции каталога — за 15 минут.</span></div><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-channel-phone" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Телефон</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)">Появится после подключения номера. Пока быстрее всего — чат в MAX.</span></div><div class="blueprint" style="padding:20px;display:flex;flex-direction:column;gap:8px"><span class="ico ico-28 i-ui-requisites" style="color:var(--color-accent-700)"></span><span style="font-family:var(--font-heading);font-weight:600;font-size:18px;line-height:1.25">Реквизиты</span><span style="font-size:15px;line-height:1.55;color:var(--color-neutral-800)">Будут опубликованы после регистрации юридического лица.</span></div></div>
<h2>Как мы отвечаем</h2><p>Заявки, отправленные вечером и в выходные, разбираются в начале следующего рабочего дня. Для поставщиков: как устроено сотрудничество — на странице «<a href="${BASE}${ROUTES.supplier.path}">Поставщикам</a>» и в «<a href="${BASE}${ROUTES.terms.path}">условиях работы</a>».</p>
${useful('kontakty/')}<p style="font-size:12px;line-height:1.5;color:var(--color-neutral-600);margin-top:36px">Сайт работает в демонстрационном режиме: формы и заказы не отправляются.</p>` },
    { path: 'politika-konfidencialnosti/', index: true, h1: 'Политика конфиденциальности', title: 'Политика конфиденциальности — ПРОМКОНТУР', desc: 'Какие данные собирает сервис ПРОМКОНТУР, зачем, как хранит и как отозвать согласие на обработку персональных данных.',
      html: note + `<h2>1. Какие данные мы обрабатываем</h2><p>Контактные данные представителя компании (имя, должность, телефон, электронная почта), реквизиты организации, состав заявок и заказов, переписку в чате и мессенджере MAX, технические данные посещения сайта (cookie, IP-адрес, тип браузера).</p>
<h2>2. Зачем</h2><p>Для подбора оборудования и подготовки коммерческих предложений, выставления счетов и исполнения договоров поставки, уведомлений о статусе заказа, проверки контрагента при открытии отсрочки, улучшения работы сайта.</p>
<h2>3. Правовые основания</h2><p>Обработка ведётся в соответствии с Федеральным законом № 152-ФЗ «О персональных данных»: на основании согласия субъекта, а также для заключения и исполнения договора, стороной которого является компания пользователя.</p>
<h2>4. Кому передаются данные</h2><p>Поставщику, который выполняет конкретный заказ, — в объёме, необходимом для отгрузки; перевозчику — адрес и контакт получателя; банку и оператору ЭДО — для расчётов и документооборота. Данные не продаются и не передаются для рекламы третьих лиц.</p>
<h2>5. Хранение и защита</h2><p>Данные хранятся на серверах, расположенных в Российской Федерации, в течение срока действия договора и срока, установленного законодательством для бухгалтерских документов. Доступ сотрудников ограничен ролями.</p>
<h2>6. Ваши права</h2><p>Вы можете запросить сведения об обработке своих данных, потребовать их уточнения или удаления и отозвать согласие, написав в чат поддержки. Ответ — в течение 10 рабочих дней.</p>
${useful('politika-konfidencialnosti/')}` },
    { path: 'usloviya-ispolzovaniya/', index: true, h1: 'Условия использования', title: 'Условия использования сервиса — ПРОМКОНТУР', desc: 'Правила использования сервиса ПРОМКОНТУР: статус информации на сайте, цены и наличие, порядок заказа, ответственность сторон.',
      html: note + `<h2>1. Сервис</h2><p>ПРОМКОНТУР — сервис подбора и закупки промышленного оборудования у независимых поставщиков. Сервис не является производителем и официальным представителем брендов, упомянутых в каталоге; товарные знаки принадлежат их правообладателям.</p>
<h2>2. Цены и наличие</h2><p>Цены в каталоге указаны с НДС и доставкой, кроме габаритных грузов и удалённых регионов, и обновляются по данным поставщиков. Окончательная цена и срок фиксируются в счёте. Позиции дороже порога и проектные поставки оформляются через коммерческое предложение.</p>
<h2>3. Заказ и оплата</h2><p>Заказ оформляется выставлением счёта или договора поставки. Отгрузка — после оплаты либо при одобренной отсрочке. Закрывающие документы направляются по ЭДО и в личный кабинет.</p>
<h2>4. Гарантия и рекламации</h2><p>Срок и условия гарантии указываются в карточке товара и определяются условиями поставщика. Порядок обращения описан на странице «<a href="${BASE}${ROUTES.warranty.path}">Гарантия, возврат и рекламации</a>».</p>
<h2>5. Отзывы и контент</h2><p>Отзыв может оставить только компания с подтверждённой покупкой. Статьи носят справочный характер и не заменяют инженерный расчёт под конкретный объект.</p>
<h2>6. Ответственность</h2><p>Сервис отвечает за корректность оформления заказа и соблюдение заявленных сроков в пределах, указанных в счёте. Ответственность поставщика за качество товара определяется договором поставки.</p>
${useful('usloviya-ispolzovaniya/')}` },
  ];
};
